Certona ca
Sephora-Email-Dev-Team/gridgenerator-react pull request #20
Opened 2022-01-25 17:55 UTC by rvrita

Added CA Certona 3x1 and have a small fix for our US Certona 3x1 (the images didn't have height and width and it caused issues sometimes).

2022-02-02 17:55 UTC, choiwa requested changes
please review the comment regarding the width and height. Thank you!

2022-02-02 17:55 UTC, choiwa commented on templates/templateC3x1CA.js
> +              <img border="0" src="http://ris.res-x.com/image.aspx?appid=Sephora02&userid=\${Profile.atg1_id!'0000'}&index=3&scheme=${tag}&campaignid=\${deploymentName}" alt="" />
@rvrita the images run larger than 700px total. can we width="190" height="306" so they will display same as the US?

2022-02-06 22:01 UTC, rvrita commented on templates/templateC3x1CA.js
> +              <img border="0" src="http://ris.res-x.com/image.aspx?appid=Sephora02&userid=\${Profile.atg1_id!'0000'}&index=3&scheme=${tag}&campaignid=\${deploymentName}" alt="" />
Thanks Joyce, added the image sizes

2022-02-07 19:28 UTC, choiwa approved these changes
looks great! Thank you.

2022-02-07 19:33 UTC, merged