checkBox refactor
Sephora-Email-Dev-Team/gridgenerator-react pull request #42
Opened 2022-04-04 03:26 UTC by rvrita

Checkbox refactor.

2022-04-04 15:54 UTC, iviondayjr commented
Awesome, I like all the props on their own line. Clean!

2022-04-04 23:17 UTC, choiwa requested changes
use 'id' for htmlFor so the buttons will be selected even texts is clicked.

2022-04-04 23:17 UTC, choiwa commented on client/src/components/InputField.jsx
> +    <label htmlFor={name}>
Instead of using 'name', using 'id' so the buttons will be selected even clicking on the texts.

`<label htmlFor={id}>`

2022-04-11 01:29 UTC, choiwa approved these changes
looks great!

2022-04-11 01:29 UTC, merged